#!/usr/bin/env python3

import hashlib
import time
import socket
import requests
import dns.resolver
import whois
import ssl

# ==============================
# 🔷 TOOL INFO
# ==============================

AUTHOR = "Benahmed Mohamed"
TOOL_NAME = "SentinelRecon"
VERSION = "1.0"

SIGNATURE = "SentinelRecon | Cyber Intelligence Tool"

SECRET_SALT = "9x!QpL@7#Secure"
INVISIBLE_MARK = "\u200b\u200c\u200d"

# ==============================
# 🔐 FINGERPRINT
# ==============================

def generate_fingerprint():
    raw = f"{AUTHOR}{TOOL_NAME}{VERSION}{time.time()}{SECRET_SALT}"
    return hashlib.sha256(raw.encode()).hexdigest()

# ==============================
# 🕵️ TRACKING (LOCAL)
# ==============================

def track_usage(domain):
    try:
        with open(".sentinel_log", "a") as f:
            f.write(f"{domain} | {time.ctime()}\n")
    except:
        pass

# ==============================
# 🌐 RECON FUNCTIONS
# ==============================

def resolve_domain(domain):
    try:
        return socket.gethostbyname(domain)
    except:
        return "Failed"

def get_dns(domain):
    try:
        records = dns.resolver.resolve(domain, 'A')
        return [r.to_text() for r in records]
    except:
        return ["Failed"]

def get_whois(domain):
    try:
        data = whois.whois(domain)
        return data.domain_name
    except:
        return "Failed"

def check_ssl(domain):
    try:
        ctx = ssl.create_default_context()
        with ctx.wrap_socket(socket.socket(), server_hostname=domain) as s:
            s.connect((domain, 443))
            cert = s.getpeercert()
            return cert['issuer']
    except:
        return "No SSL"

def check_http(domain):
    try:
        res = requests.get(f"http://{domain}", timeout=5)
        return res.status_code
    except:
        return "No response"

# ==============================
# 🚀 MAIN SCAN
# ==============================

def sentinel_scan(domain):
    print("="*50)
    print(f"{SIGNATURE}")
    print(f"{INVISIBLE_MARK}{AUTHOR}{INVISIBLE_MARK}")
    print("="*50)

    fp = generate_fingerprint()
    print(f"[ID] {fp[:16]}")
    print(f"[Target] {domain}")

    ip = resolve_domain(domain)
    print(f"[IP] {ip}")

    dns_data = get_dns(domain)
    print(f"[DNS] {dns_data}")

    whois_data = get_whois(domain)
    print(f"[WHOIS] {whois_data}")

    ssl_data = check_ssl(domain)
    print(f"[SSL] {ssl_data}")

    http_status = check_http(domain)
    print(f"[HTTP] {http_status}")

    track_usage(domain)

    print("="*50)
    print("Scan Complete ✅")
    print(f"Generated by {AUTHOR}")
    print("="*50)

# ==============================
# ▶️ RUN
# ==============================

if __name__ == "__main__":
    target = input("Enter domain: ")
    sentinel_scan(target)
